module.exports = {
  content: ["./build/**/*.{html,js}"],
  separator: '_',
  theme: {
    screens: {
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      xxl: '1440px',
      '3xl': '1800px'
    },
    container: {
      center: true,
      padding: {
        DEFAULT: '20px',
        xl: '64px',
        xxl: '64px'
      },
    },
    fontSize: {
      xs: ['0.75rem', { lineHeight: '1rem' }],
      sm: ['14px', { lineHeight: '24px' }],
      '15': ['15px', { lineHeight: '21px' }],
      base: ['16px', { lineHeight: '26px' }],
      lg: ['1.125rem', { lineHeight: '1.75rem' }],
      xl: ['20px', { lineHeight: '30px' }],
      '2xl': ['24px', { lineHeight: '32px' }],
      '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
      '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
      '5xl': ['3rem', { lineHeight: '1' }],
      '6xl': ['3.75rem', { lineHeight: '1' }],
      '7xl': ['4.5rem', { lineHeight: '1' }],
      '8xl': ['6rem', { lineHeight: '1' }],
      '9xl': ['8rem', { lineHeight: '1' }],
    },
    colors: ({ colors }) => ({
      inherit: colors.inherit,
      current: colors.current,
      transparent: colors.transparent,
      black: '#14142B',
      slate: '#181828',
      white: '#fff',
      neutral: colors.neutral,
      red: '#ff0000',
      orange: colors.orange,
      amber: colors.amber,
      yellow: colors.yellow,
      lime: colors.lime,
      green: colors.green,
      emerald: colors.emerald,
      teal: colors.teal,
      cyan: colors.cyan,
      sky: colors.sky,
      blue: colors.blue,
      indigo: colors.indigo,
      violet: colors.violet,
      purple: colors.purple,
      fuchsia: colors.fuchsia,
      pink: colors.pink,
      rose: colors.rose,
      gray: {
        50: '#f9fafb',
        100: '#f5f5f5',
        200: '#ebebeb',
        300: '#D3D3D3',
        400: '#9ca3af',
        500: '#686868',
        600: '#4b5563',
        700: '#374151',
        800: '#1f2937',
        900: '#14142B',
      },
    }),
    fontFamily: {
      sans: [
        '-apple-system',
        'BlinkMacSystemFont',
        'Circe',
        'ui-sans-serif',
        'system-ui',
        '"Segoe UI"',
        'Roboto',
        '"Helvetica Neue"',
        'Arial',
        '"Noto Sans"',
        'sans-serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      serif: ['ui-serif', 'Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
      mono: [
        'ui-monospace',
        'SFMono-Regular',
        'Menlo',
        'Monaco',
        'Consolas',
        '"Liberation Mono"',
        '"Courier New"',
        'monospace',
      ],
      icon: [
        '"Font Awesome 6 Free"'
      ]
    },
    boxShadow: {
      sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
      default: '0px 0px 14px rgba(0, 0, 0, 0.1)',
      md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
      lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
      xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
      '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
      inner: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)',
      none: 'none',
    },
    extend: {
      spacing: {
        '3px':  '3px',
        '5px':  '5px',
        '8px': '8px',
        '10px': '10px',
        '15px': '15px',
        '16px': '16px',
        '20px': '20px',
        '30px': '30px',
        '40px': '40px',
        '60px': '60px',
        '80px': '80px',
        '100px': '100px',
        '110px': '110px',
        '120px': '120px',
        '140px': '140px',
        '150px': '150px',
        '160px': '160px',
        '170px': '170px',
        '180px': '180px',
        '402px': '402px',
        '466px': '466px',
        '736px': '736px'
      },
    },
  },
  plugins: [],
}
